language: common-lisp

sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t/:src/error.lisp
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin

install:
  # Install Roswell
  - if ! $(which ros >/dev/null); then
      curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh;
    else
      ros -e '(ql:update-all-dists :prompt nil)';
    fi
  - ros install prove

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - run-prove fast-websocket-test.asd
