language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t/:src/error.lisp
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=allegro
    - LISP=cmucl

matrix:
  allow_failures:
    # 'clisp' requires 'sudo' because it's not in the whitelist of APT packages.
    - env: LISP=clisp
    - env: LISP=allegro
    - env: LISP=cmucl

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre
      - clisp
      - libc6-dev-i386
      - libffi-dev

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros -e '(ql:update-all-dists :prompt nil)'
  - ros install prove

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - run-prove fast-websocket-test.asd
